routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@home')->name('index.index');

Route::get('/tags/{tagname}',function($tagname){
    return $tagname;
});

Route::get('routes', function(){
    return view('routes');
});

Route::group(['middleware' => 'auth'], function(){
    Route::resource('category', 'CategoryController');
    Route::resource('tag', 'TagController');
});
Route::resource('comment', 'CommentController');

Route::resource('post', 'PostController');//->middleware('can:resource,post');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/welcome', function (){
    return view('welcome');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Symfony\Component\Console\Tests\Command\CommandTest;

class Post extends Model
{

    protected $fillable =[
        'user_id', 'category_id', 'title', 'text', 'image'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

//    public static function owns($relatd , $post)
//    {
////        if (($relatd->user->id == $this->id) || ($relatd->user->admin == '1'))
////            return true;
//        return $relatd->id == $post->user_id;
//    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Comment;
use App\Http\Requests\PostRequest;
use App\Post;
use App\Tag;
use Gate;

class PostController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public $path = 'img/upload/';

    public function __construct()
    {
//        $this->middleware('auth', ['except' => ['show']]);
    }

    public function index()
    {
        $posts = Post::get();
//        Gate::denies('post');
//        Gate::allows('post');

        return view('post.index', compact('posts', 'comments', 'cats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        $user = '1';

//        $this->authorize('create', post::class);//work

//        $this->authorize('create-post', "$user");
//        if(Gate::denies('create'))
//            abort(404, 'hihi');

        $categories = Category::pluck('name', 'id');
        $tags = Tag::pluck('name', 'id');
        return view('post.create2', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        $picname = $request->file('image')->getClientOriginalName();
//        $rand = rand(1000000 , 9000000);
//        $picname = $picname.$rand;
        $request->image->move($this->path, $picname);
        $picname = $this->path . $picname;
        $inputs = $request->all();
        $inputs['image'] = $picname;
        auth()->user()->Posts()->create($inputs)->tags()->sync($inputs['tag_id']);

        return redirect(route('post.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
//        $this->authorize('update', $post);//work

//        if(Gate::denies('edit-post', $post))
//            abort(404,'post male shoma nist') ;

        $categories = Category::pluck('name', 'id');
        $tags = Tag::pluck('name', 'id');
        return view('post.edit', compact('post', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, Post $post)
    {
        $picname = $request->file('image')->getClientOriginalName();
////        $rand = rand(1000000 , 9000000);
////        $picname = $picname.$rand;
        $request->image->move($this->path, $picname);
        $inputs = $request->all();
        $inputs['image'] = $this->path . $picname;
        $post->update($inputs);
        $post->tags()->sync($inputs['tag_id']);

        return redirect(route('post.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->back();
    }
}

resources/views/post/create.blade.php
@extends('layouts.layout')
@section('content')

    @if(Session::has('title_massage'))
        @include('partials.flash')
    @endif

    <form action="{{ route('post.store') }}" method="POST" role="form" enctype="multipart/form-data">
        {{ csrf_field() }}
        <legend>افزودن پست جدید:</legend>
        <input type="hidden" name="user_id" value="1">

        <div class="form-group">
            <select name="category_id" class="form-control">
                @foreach( $categories as $category_id => $category)
                    <option value="{{ $category_id }}"> {{ $category }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <input type="text" title="title" class="form-control" name="title" id=""
                   value="@if(Session::has('title')) {{ Session::get('title') }} @endif" placeholder="عنوان...">
        </div>
        <div class="form-group">
        <textarea type="text" title="text" class="form-control" name="text" id=""
                  value="@if(Session::has('text')) {{ Session::get('text') }} @endif" placeholder="متن..."></textarea>
        </div>

        <div class="form-group">
            <select name="tag_id[]" class="form-control" multiple>
                <option></option>
                @foreach( $tags as $tag)
                    <option value="{{ $tag->id }}"> {{ $tag->name }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <span>عکس پست:</span>
            <input type="file" name="image" title="تصویر شاخص"
                   value="@if(Session::has('image')) {{ Session::get('image') }} @endif">
        </div>

        <div>
            <button type="submit" class="btn btn-success">انتشار</button>
            <a href="{{ route('post.index') }}" class="btn btn-danger">لغو</a>
            <a href="{{ route('tag.create') }}" class="btn btn-default">ساختن تگ جدید</a>
        </div>
    </form>

@endsection

resources/views/post/create2.blade.php
@extends('layouts.layout')
@section('content')
    <div class="col-md-8 col-md-offset-2">
        @if($errors)
            <ul>
                @foreach ($errors->all() as $error)
                    <li class="alert alert-danger">{{ $error }}</li>
                @endforeach
            </ul>
        @endif
        {!! Form::open(['route' => 'post.store', 'files' => true]) !!}
        <h2>افزودن پست جدید:</h2>

            @can('create', \App\Post::class)

            @include('post.fields')

            @endcan

        {!! Form::close() !!}
    </div>

    @push('footer')
        <script type="text/javascript" src="{{ asset('editor/full/ckeditor/ckeditor.js') }}"></script>
        <script type="text/javascript" src="{{ asset('editor/full/ckeditor/adapters/jquery.js') }}"></script>
        <script>
            $( document ).ready( function() {
                $( 'textarea#editor1' ).ckeditor();
            } );
        </script>
    @endpush
@endsection

resources/views/post/edit.blade.php
@extends('layouts.layout')
@section('content')
    <div class="col-md-8 col-md-offset-2">

        {!! Form::model($post, ['route'=>['post.update', $post->id ], 'method' => 'patch', 'files' => true ]) !!}
        <h2>ویرایش پست:</h2>

        @include('post.fields')

        {!! Form::close() !!}

    </div>

    @push('footer')
        <script type="text/javascript" src="{{ asset('editor/full/ckeditor/ckeditor.js') }}"></script>
        <script type="text/javascript" src="{{ asset('editor/full/ckeditor/adapters/jquery.js') }}"></script>
        <script>
            $( document ).ready( function() {
                $( 'textarea#editor1' ).ckeditor();
            } );
        </script>
    @endpush
@endsection

resources/views/post/fields.blade.php
<!-- فیلد دسته -->
<div class="form-group {{ $errors->has('category_id') ? ' has-error' : '' }}">
    {!! Form::label('category_id', 'دسته') !!}
    {!! Form::select('category_id', $categories, null, ['class' => 'form-control']) !!}
    @if ($errors->has('category_id'))
        <span class="help-block"><strong>{{ $errors->first('category_id') }}</strong></span>
    @endif
</div>

<!-- فیلد عنوان -->
<div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
    {!! Form::label('title', 'عنوان') !!}
    {!! Form::text('title', null, ['class' => 'form-control']) !!}
    @if ($errors->has('title'))
        <span class="help-block"><strong>{{ $errors->first('title') }}</strong></span>
    @endif
</div>

<div>برای نوشتن میتوانید از <a href="https://wordtohtml.net/">ویرایش گر آنلاین</a> استفاده نمایید.</div>

<!-- فیلد متن پست -->
<div class="form-group {{ $errors->has('text') ? ' has-error' : '' }}">
    {!! Form::label('text', 'متن پست') !!}
    {!! Form::textarea('text', null, ['class' => 'form-control', 'id'=>'editor1']) !!}
    @if ($errors->has('text'))
        <span class="help-block"><strong>{{ $errors->first('text') }}</strong></span>
    @endif
</div>

<!-- فیلد تگ -->
<div class="form-group {{ $errors->has('tag_id[]') ? ' has-error' : '' }}">
    {!! Form::label('tag_id[]', 'تگ') !!}
    {!! Form::select('tag_id[]', $tags , (isset($post))?$post->tags:null , ['class' => 'form-control', 'multiple' => true ]) !!}
    @if ($errors->has('tag_id[]'))
        <span class="help-block"><strong>{{ $errors->first('tag_id[]') }}</strong></span>
    @endif
</div>


<div class="form-group">
    {!! Form::label('image', 'عکس پست') !!}
    {!! Form::file('image', ['class' => 'form-control']) !!}
</div>
{{--chape errore ax ziresh--}}

<div>
        <button type="submit" class="btn btn-success">انتشار</button>
        <a href="{{ route('post.index') }}" class="btn btn-danger">لغو</a>
        <a href="{{ route('tag.create') }}" class="btn btn-default">ساختن تگ جدید</a>
</div>

resources/views/post/index.blade.php
@extends('layouts.layout')
@section('content')

    <a href="{{ route('post.create') }}" class="btn btn-primary">اضافه کردن پست جدید</a>
    <hr>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>عنوان</th>
            <th>نویسنده</th>
            <th>دسته بندی</th>
            <th>نمایش نوشته</th>
            <th>عملیات:</th>
        </tr>
        </thead>
        <tbody>

        @foreach($posts as $post)
{{--            @can('edit-post', $post)--}}
                <tr>
                    <td>{{ $post->title }}</td>
                    <td>{{ $post->user->name }}</td>
                    <td>{{ $post->category->name }}</td>
                    <td><a href="{{ route('post.show', $post->id) }}">بیشتر...</a></td>

                    <td>
                        <a href="{{ route('post.edit', $post->id) }}" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                        <form style="display: inline" action="{{ route('post.destroy', $post->id) }}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>
                    </td>
                </tr>
            {{--@endcan--}}
        @endforeach

        </tbody>
    </table>

@endsection

resources/views/post/show.blade.php
@extends('layouts.layout')
@section('content')
    @include('partials.header')

    @can('edit-post', $post)
        <div style="color: #831700; font-size:large" class="pull-left">
            <a href="{{route('post.edit', $post->id)}}">
                ویرایش پست
            </a>
        </div>
    @endcan
    <div class="col-md-12" align="center">
        <img src="/{{ $post->image }}">
    </div>

    <div class="container post">
        <div class="row">
            <div class="col-md-12 post-title">
                <h1>{{ $post->title }}</h1>
                <p class="author"><strong>{{ $post->user->name }}</strong> <span
                            class="text-muted">اخرین ویرایش: {{ $post->updated_at }} </span></p>
            </div>
            <div class="col-md-12 col-md-offset-0 post-body">
                {!! $post->text !!}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-6">
                <h2>دیدگاه ها:</h2>
                @if($post->comments == '[]')
                    <div style="font-size: small; color: #5a5a5a">دیدگاهی برای این نوشته وجود ندارد.</div>
                @else
                    @foreach($post->comments as $comment)
                        <span style="color: #2d3a83; font-size:small">{{ $comment->name }}
                            میگه:
                        </span>
                        @can('edit-comment', $comment)
                            <span style="color: #831700; font-size:xx-small" class="pull-left">
                                <a href="{{route('comment.edit', $comment->id)}}">
                                ویرایش
                                </a>
                            </span>
                            {{--<br>--}}
                        @endcan
                        <div style="margin-right: 50px; border-bottom: 0.5px dashed rgba(0,0,0,0.17)">{!! $comment->text !!}</div>
                    @endforeach
                @endif
                <hr>
                <h2>دسته بندی:</h2>
                <div><a href="{{route('category.index')}}/{{$post->category->id}}">{{$post->category->name}}</a></div>
                <hr>
                <h2>برچسب ها:</h2>
                @foreach($post->tags as $tag)
                    <div><a href="{{route('tag.index')}}/{{ $tag->id }}">{{ $tag->name }}</a></div>
                @endforeach
            </div>

            <div class="col-md-6">


                {!! Form::open(['route'=>['comment.store', 'post_id' => $post->id ], 'method' => 'post']) !!}

                @if(Auth::check())
                    <div>
                            <span style="color: rgba(90,90,90,0.48)">
                                وارد شده با نام کاربری:
                            </span>
                        <span>{{ auth()->user()->name }}</span>
                    </div>

                @else

                <!-- فیلد نام شما -->
                    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                        {!! Form::label('name', 'نام شما:') !!}
                        {!! Form::text('name', null, ['class' => 'form-control']) !!}
                        @if ($errors->has('name'))
                            <span class="help-block"><strong>{{ $errors->first('name') }}</strong></span>
                        @endif
                    </div>
                @endif

            <!-- فیلد افزودن دیدگاه: -->
                <div class="form-group {{ $errors->has('text') ? ' has-error' : '' }}">
                    {!! Form::label('text', 'افزودن دیدگاه:') !!}
                    <br>
                    {!! Form::textarea('text', null, ['class' => 'form-control', 'id'=> 'editorcm']) !!}
                    @if ($errors->has('text'))
                        <span class="help-block"><strong>{{ $errors->first('text') }}</strong></span>
                    @endif
                </div>
                <button class="btn btn-success">ثبت دیدگاه</button>
                {!! Form::close() !!}

            </div>
        </div>
    </div>

    @push('footer')
        <script type="text/javascript" src="{{ asset('editor/basic/ckeditor/ckeditor.js') }}"></script>
        <script type="text/javascript" src="{{ asset('editor/basic/ckeditor/adapters/jquery.js') }}"></script>
        <script>
            $(document).ready(function () {
                $('textarea#editorcm').ckeditor();
            });
        </script>
    @endpush
    @include('partials.footer')
@endsection