routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@home')->name('index.index');

Route::get('/tags/{tagname}',function($tagname){
    return $tagname;
});

Route::get('routes', function(){
    return view('routes');
});

Route::group(['middleware' => 'auth'], function(){
    Route::resource('category', 'CategoryController');
    Route::resource('tag', 'TagController');
});
Route::resource('comment', 'CommentController');

Route::resource('post', 'PostController');//->middleware('can:resource,post');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/welcome', function (){
    return view('welcome');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public $timestamps=false;
    protected $fillable =[
        'name'
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Gate;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        if ( Gate::denies('edit-tag-and-category'))
            abort(404,  'you are not admin');

        $categories = Category::all();
        return view('category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if ( Gate::denies('edit-tag-and-category'))
            abort(404,  'you are not admin');

        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Category::create($request->all());
        return redirect(route('category.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)//show all category's posts
    {
        if ( Gate::denies('edit-tag-and-category'))
            abort(404,  'you are not admin');

        $posts = $category->posts()->orderBy('updated_at' , 'desc')->paginate(6);
        return view('index', compact('posts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        if ( Gate::denies('edit-tag-and-category'))
            abort(404,  'you are not admin');

        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $category->update($request->all());
        return redirect(route('category.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->back();
    }
}

resources/views/category/create.blade.php
@extends('layouts.layout')
@section('content')

    <form action="{{ route('category.store') }}" method="POST" role="form">
        {{ csrf_field() }}
        <legend>افزودن دسته جدید:</legend>

        <div class="form-group">
            <input type="text" title="text" class="form-control" name="name" id="" placeholder="نام دسته...">
        </div>
        <div>
            <button type="submit" class="btn btn-success">ثبت</button>
            <a href="{{ route('category.index') }}" class="btn btn-danger">لغو</a>
        </div>
    </form>

@endsection

resources/views/category/edit.blade.php
@extends('layouts.layout')
@section('content')

    <form action="{{ route('category.update', $category->id) }}" method="POST" role="form">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
    	<legend>ویرایش دسته</legend>

    	<div class="form-group">
    		<label for=""></label>
    		<input type="text" class="form-control" name="name" id="" value="{{ $category->name }}" placeholder="Input...">
    	</div>
    	<button type="submit" class="btn btn-success">ثبت ویرایش</button>
    </form>

@endsection

resources/views/category/index.blade.php
@extends('layouts.layout')
@section('content')

    <a href="{{ route('category.create') }}" class="btn btn-primary">اضافه کردن دسته جدید</a>
    <hr>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>گروه بندی نوشته ها:</th>
            <th>عملیات:</th>
        </tr>
        </thead>
        <tbody>

        @foreach($categories as $category)
            <tr>
                <td>{{ $category->name }}</td>
                <td>
                    <a href="{{ route('category.edit', $category->id) }}" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                    <form style="display: inline" action="{{ route('category.destroy', $category->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>

@endsection