routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@home')->name('index.index');

Route::get('/tags/{tagname}',function($tagname){
    return $tagname;
});

Route::get('routes', function(){
    return view('routes');
});

Route::group(['middleware' => 'auth'], function(){
    Route::resource('category', 'CategoryController');
    Route::resource('tag', 'TagController');
});
Route::resource('comment', 'CommentController');

Route::resource('post', 'PostController');//->middleware('can:resource,post');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/welcome', function (){
    return view('welcome');
});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable =[
        'name', 'user_id', 'post_id', 'text'
    ];

    public function post()
    {
        return $this->belongsTo(Post::class);
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use Auth;
use Gate;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function aclcheck()
    {
        if ( Gate::denies('edit-tag-and-category'))
            abort(404,  'you are not admin');
    }

    public function __construct()
    {
        $this->middleware('auth', ['except' => ['store']]);
    }

    public function index()
    {
        $this->aclcheck();

        $comments = Comment::all();

        return view('comment.index', compact('comments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //We don't need it. it will create in post/show view.
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Auth::check()){
            $request['name'] = auth()->user()->name;
            $request['user_id'] = auth()->user()->id;
        }
        else{
            $request['name'] = $request['name'] . ' (کاربر مهمان) ';
            $request['user_id'] = null;
        }
        Comment::create($request->all());

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Comment $comment)
    {
        return view('comment.show', compact('comment'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $comment)
    {
        $this->aclcheck();

        return view('comment.edit', compact('comment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $comment)
    {
        if (Auth::check()){
            $request['name'] = auth()->user()->name;
            $request['user_id'] = auth()->user()->id;
        }
        else{
            $request['name'] = $request['name'] . ' (کاربر مهمان) ';
            $request['user_id'] = null;
        }

        $comment->update($request->all());

        return redirect(route('comment.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $comment->delete();

        return redirect()->back();
    }
}

resources/views/comment/create.blade.php
@extends('layouts.layout')
@section('content')

    <form action="{{ route('comment.store') }}" method="POST" role="form">
        {{ csrf_field() }}
        <legend>افزودن دیدگاه جدید:</legend>
        <input type="hidden" name="post_id" value="3" >

        <div class="form-group">
            <input type="text" title="text" class="form-control" name="name" id="" placeholder="نام شما...">
        </div>
        <div class="form-group">
            <textarea type="text" title="text" class="form-control" name="text" id="" placeholder="دیدگاه..."></textarea>
        </div>
        <div>
            <button type="submit" class="btn btn-success">انتشار</button>
            <a href="{{ route('comment.index') }}" class="btn btn-danger">لغو</a>
        </div>
    </form>

@endsection

resources/views/comment/edit.blade.php
@extends('layouts.layout')
@section('content')

    <form action="{{ route('comment.update', $comment->id) }}" method="POST" role="form">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
    	<legend>ویرایش  دیدگاه</legend>

		<div class="form-group">
			<input type="text" title="text" class="form-control" value="{{ $comment->post_id }}" name="category_id" id="" placeholder="نام دسته...">
		</div>
		<div class="form-group">
			<input type="text" title="text" class="form-control" value="{{ $comment->name }}" name="title" id="" placeholder="عنوان...">
		</div>
		<div class="form-group">
			<textarea type="text" title="text" class="form-control" name="text" id="" >{{ $comment->text }}</textarea>
		</div>

    	<button type="submit" class="btn btn-success">ثبت ویرایش</button>
    </form>

@endsection

resources/views/comment/index.blade.php
@extends('layouts.layout')
@section('content')

    <table class="table table-hover">
        <thead>
        <tr>
            <th>متن دیدگاه</th>
            <th>نویسنده</th>
            <th>پست</th>
            <th>عملیات:</th>
        </tr>
        </thead>
        <tbody>

        @foreach($comments as $comment)
            @can('edit-comment', $comment)
                <tr>
                    <td>{{ $comment->text }}</td>
                    <td>{{ $comment->name }}</td>
                    <td><a href="{{route('post.show' ,$comment->post->id)}}">{{ $comment->post->title }}</a></td>
                    <td>
                        <a href="{{ route('comment.edit', $comment->id) }}" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                        <form style="display: inline" action="{{ route('comment.destroy', $comment->id) }}"
                              method="post">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>
                    </td>
                </tr>
            @endcan
        @endforeach

        </tbody>
    </table>

@endsection