routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@home')->name('index.index');

Route::get('/tags/{tagname}',function($tagname){
    return $tagname;
});

Route::get('routes', function(){
    return view('routes');
});

Route::group(['middleware' => 'auth'], function(){
    Route::resource('category', 'CategoryController');
    Route::resource('tag', 'TagController');
});
Route::resource('comment', 'CommentController');

Route::resource('post', 'PostController');//->middleware('can:resource,post');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/welcome', function (){
    return view('welcome');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public $timestamps=false;
    protected $fillable =[
        'name'
    ];

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Policies\TagPolicy;
use App\Tag;
use Illuminate\Http\Request;
Use Gate;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function aclcheck()
    {
        if ( Gate::denies ('edit-tag-and-category' ) )
            abort (404,  'you are not admin' ) ;
    }

//    public function __construct()
//    {
//        if ( Gate::denies('edit-tag-and-category'))
//            abort(404,  'you are not admin');
//    }

    public function index()
    {
        $this->aclcheck();

//        if ( Gate::denies('edit-tag-and-category'))
//            abort(404,  'you are not admin');

//        if ( Gate::denies('update'))
//            abort(404,  'you are not admin');

        $tags = Tag::all();

        return view('tag.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->aclcheck();
        return view('tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Tag::create($request->all());

        return redirect(route('tag.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tag $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        $posts = $tag->posts()->paginate(6);

        return view('index', compact('posts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tag $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        $this->aclcheck();
        return view('tag.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Tag $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        $tag->update($request->all());

        return redirect(route('tag.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tag $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();

        return redirect()->back();
    }
}

resources/views/tag/create.blade.php
@extends('layouts.layout')
@section('content')

    {{--<form action="{{ route('tag.store') }}" method="POST" role="form">--}}
        {{--{{ csrf_field() }}--}}

    {!! Form::open(['route'=>['tag.store']]) !!}
        <!-- فیلد نام تگ -->
        <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
            {!! Form::label('name', 'نام تگ:') !!}
            {!! Form::text('name', null, ['class' => 'form-control']) !!}
            @if ($errors->has('name'))
                <span class="help-block"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>

        <div>
            <button type="submit" class="btn btn-success">ثبت</button>
            <a href="{{ route('tag.index') }}" class="btn btn-danger">لغو</a>
        </div>
    {!! Form::close() !!}

    {{--</form>--}}

@endsection

resources/views/tag/edit.blade.php
@extends('layouts.layout')
@section('content')

    <form action="{{ route('tag.update', $tag->id) }}" method="POST" role="form">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
    	<legend>ویرایش تگ</legend>

    	<div class="form-group">
    		<label for=""></label>
    		<input type="text" class="form-control" name="name" id="" value="{{ $tag->name }}" placeholder="Input...">
    	</div>
    	<button type="submit" class="btn btn-success">ثبت ویرایش</button>
    </form>

@endsection

resources/views/tag/field.blade.php
@extends('layouts.layout')
@section('content')


@endsection

resources/views/tag/index.blade.php
@extends('layouts.layout')
@section('content')

    <a href="{{ route('tag.create') }}" class="btn btn-primary">اضافه کردن تگ جدید</a>
    <hr>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>تگ نوشته ها:</th>
            <th>عملیات:</th>
        </tr>
        </thead>
        <tbody>

        @foreach($tags as $tag)
            <tr>
                <td>{{ $tag->name }}</td>
                <td>
                    <a href="{{ route('tag.edit', $tag->id) }}" class="btn btn-default btn-sm">
                        <span class=" glyphicon glyphicon-edit"></span>
                    </a>
                    <form style="display: inline" action="{{ route('tag.destroy', $tag->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>

@endsection

resources/views/tag/show.blade.php
@extends('layouts.layout')
@section('title', 'این یک وبلاگ ساده است!')
@section('content')

    @include('partials.header')

    <div id="posts">
        @foreach($posts as $post)
            <div id="post">
                <span id="title"><a href="{{ route('post.index') }}/{{ $post->id }}">{{ $post->title }}</a></span>
                <br>
                <a href="{{ route('post.index') }}/{{ $post->id }}"><img
                            src="{{ route('index.index') }}/{{ $post->image }}" alt=""></a>
                <br>
                <div id="text">{{ $post->text }}</div>
                <div>{{ $post->created_at }}</div>
            </div>
        @endforeach
    </div>

    <div align="center">
        {{--{{ $posts->render() }}--}}
    </div>


    @include('partials.footer')
@endsection